### ISSUE TITLE
Add package-lock.json to .gitignore

### ISSUE THREAD

**Issue by haxwell** [savvato-software/dtim-mobile#16]
So ensure that changes to the file do not make it appear in the `git status` list.

**Comment by braydenc303** [comment]
After reading [this post](https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore) perhaps we should instead leave the package-lock.json, but switch our install process to use npm ci instead.

**Comment by haxwell** [comment]
Yeah, that explanation seems pretty on-point. I didn't even know about the `npm ci` command. 

Okay, well let's scrap this issue, and explore using the advice from the stackoverflow post that you linked to.
